#!/usr/bin/env python3
"""
Build supabase/_run_all.sql from migrations/*.sql with idempotent guards.

Transforms:
  create type X as enum (...);         → DO block that skips if type exists
  create table X (...)                 → create table if not exists X (...)
  create unique index ... on ...       → create unique index if not exists ...
  create index ... on ...              → create index if not exists ...
  create trigger ... on ...            → drop trigger if exists + create trigger
  alter type X add value 'v'           → DO block that skips if value exists

Safe to run repeatedly on the same database.
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).parent
MIG = HERE / "migrations"
OUT = HERE / "_run_all.sql"

# Migration files in order.
FILES = sorted(MIG.glob("[0-9][0-9][0-9][0-9]_*.sql"))

RE_CREATE_TYPE = re.compile(
    r"^create\s+type\s+(public\.)?([a-z_][a-z0-9_]*)\s+as\s+enum\s*\((.*?)\);",
    re.IGNORECASE | re.DOTALL | re.MULTILINE,
)
RE_CREATE_TABLE = re.compile(
    r"^create\s+table\s+(?!if\s+not\s+exists)(public\.[a-z_][a-z0-9_]*)",
    re.IGNORECASE | re.MULTILINE,
)
RE_CREATE_INDEX = re.compile(
    r"^(create\s+(?:unique\s+)?index)\s+(?!if\s+not\s+exists)([a-z_][a-z0-9_]*)\s+on",
    re.IGNORECASE | re.MULTILINE,
)
RE_CREATE_TRIGGER = re.compile(
    r"^(create\s+trigger\s+)([a-z_][a-z0-9_]*)\s+((?:before|after|instead\s+of)[\s\S]*?on\s+(public\.[a-z_][a-z0-9_]*))",
    re.IGNORECASE | re.MULTILINE,
)
RE_ALTER_TYPE_ADD = re.compile(
    r"^alter\s+type\s+(public\.)?([a-z_][a-z0-9_]*)\s+add\s+value\s+('[^']+')\s*;",
    re.IGNORECASE | re.MULTILINE,
)
RE_CREATE_POLICY = re.compile(
    r'^(create\s+policy\s+)("(?:[^"]|"")+"|[a-z_][a-z0-9_]*)\s+on\s+(public\.[a-z_][a-z0-9_]*)',
    re.IGNORECASE | re.MULTILINE,
)
# Seed inserts: wrap whole insert (up to terminating ";") in guard that checks
# whether the target table already has rows. If yes, skip the insert.
RE_INSERT_BLOCK = re.compile(
    r"^insert\s+into\s+(public\.[a-z_][a-z0-9_]*)[\s\S]*?;\s*$",
    re.IGNORECASE | re.MULTILINE,
)


def guard_create_type(m: re.Match) -> str:
    schema = m.group(1) or ""
    name = m.group(2)
    body = m.group(3).strip()
    return (
        f"do $$ begin\n"
        f"  create type {schema}{name} as enum ({body});\n"
        f"exception when duplicate_object then null;\n"
        f"end $$;"
    )


def add_table_if_not_exists(m: re.Match) -> str:
    return f"create table if not exists {m.group(1)}"


def add_index_if_not_exists(m: re.Match) -> str:
    return f"{m.group(1)} if not exists {m.group(2)} on"


def guard_trigger(m: re.Match) -> str:
    trg = m.group(2)
    table = m.group(4)
    return (
        f"drop trigger if exists {trg} on {table};\n"
        f"{m.group(1)}{trg} {m.group(3)}"
    )


def guard_alter_type_add(m: re.Match) -> str:
    schema = m.group(1) or ""
    name = m.group(2)
    val = m.group(3)
    return (
        f"do $$ begin\n"
        f"  alter type {schema}{name} add value {val};\n"
        f"exception when duplicate_object then null;\n"
        f"end $$;"
    )


def guard_policy(m: re.Match) -> str:
    pol = m.group(2)
    tbl = m.group(3)
    return f"drop policy if exists {pol} on {tbl};\n{m.group(1)}{pol} on {tbl}"


def guard_seed_insert(m: re.Match) -> str:
    tbl = m.group(1)
    body = m.group(0).rstrip().rstrip(";")
    return (
        f"do $$ begin\n"
        f"  if (select count(*) from {tbl}) = 0 then\n"
        f"    {body};\n"
        f"  end if;\n"
        f"end $$;"
    )


def transform(sql: str, *, seed_guard: bool = False) -> str:
    sql = RE_CREATE_TYPE.sub(guard_create_type, sql)
    sql = RE_CREATE_TABLE.sub(add_table_if_not_exists, sql)
    sql = RE_CREATE_INDEX.sub(add_index_if_not_exists, sql)
    sql = RE_CREATE_TRIGGER.sub(guard_trigger, sql)
    sql = RE_ALTER_TYPE_ADD.sub(guard_alter_type_add, sql)
    sql = RE_CREATE_POLICY.sub(guard_policy, sql)
    if seed_guard:
        sql = RE_INSERT_BLOCK.sub(guard_seed_insert, sql)
    return sql


def main() -> None:
    parts: list[str] = [
        "-- =========================================================================",
        "-- MBG Soe · consolidated migrations (idempotent).",
        "-- Generated by supabase/_build_run_all.py — DO NOT EDIT BY HAND.",
        "-- Source: supabase/migrations/*.sql (in order).",
        "-- Safe to re-run: enums, tables, indexes, and triggers use guards.",
        "-- =========================================================================",
        "",
        "begin;",
        "",
    ]
    for f in FILES:
        # Seed files (inserts that would duplicate if re-run) get a row-count
        # guard per insert. Schema/function files don't need it.
        is_seed = "seed" in f.name.lower()
        parts.append(f"-- >>> {f.name} " + "=" * (70 - len(f.name)))
        parts.append(transform(f.read_text(), seed_guard=is_seed))
        parts.append("")
    parts.append("commit;")
    parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(FILES)} files)")


if __name__ == "__main__":
    main()
