-- =============================================================================
-- 0024 · Costing Sync (Apr 2026) · enum MINYAK + 17 suppliers Excel
-- -----------------------------------------------------------------------------
-- Source: ADJUSTED Costing Sheet Dish 06042026.xlsx
-- Sheets: Ingredients List (44), Supplier List (17), Price List (137 obs)
--
-- Changes:
--  1. price_commodity enum: + MINYAK
--  2. suppliers: upsert 17 baris dengan id SUP-E01..SUP-E17
-- =============================================================================

-- 1. Enum MINYAK (idempotent via duplicate_object catch)
do $$ begin
  alter type public.price_commodity add value if not exists 'MINYAK';
exception when duplicate_object then null;
end $$;

-- 2. Upsert suppliers from Excel
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E01', 'UD Karya Sukses', 'UD'::public.supplier_type, 'Rice', null, '0812xxxx', 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E02', 'CV Triantanta Jaya ( Wijaya)', 'CV'::public.supplier_type, 'Dry condiments & salt & rice & cooking oil & frozen chicken & others', null, '0813xxxx', 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E03', 'Toko Glory', 'TOKO'::public.supplier_type, 'Dry condiments & rice & salt & cooking oil & eggs & frozen chicken', 'Mety', '081237590717', 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E04', 'Kios Louis', 'KIOS'::public.supplier_type, 'Dry condiments & cooking oil', null, '0856xxxx', 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E05', 'Blivo', 'INFORMAL'::public.supplier_type, 'Vegetables & Fruits', null, '0857xxxx', 'Jl. Palapa No.14, Oebobo, Kec. Oebobo, Kota Kupang, Nusa Tenggara Timur', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E06', 'TLM', 'INFORMAL'::public.supplier_type, 'Eggs', null, '0899xxxx', 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E07', 'Green Young Cooperative', 'KOPERASI'::public.supplier_type, 'Vegetables & Eggs & Fruits', null, '(0380) 833203', 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E08', 'Bulog', 'BUMN'::public.supplier_type, 'Rice', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E09', 'PT Alger Karya Pratama', 'PT'::public.supplier_type, 'Fish (Tuna)', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E10', 'CV Philia', 'CV'::public.supplier_type, 'Banana', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E11', 'Tunmuni Farmers Group', 'POKTAN'::public.supplier_type, 'Vegetables & Eggs', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E12', 'CV Nusantara Pangan Distributor', 'CV'::public.supplier_type, 'Rice', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E13', 'Toko Maju Lancar', 'TOKO'::public.supplier_type, 'Tofu & Tempe', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E14', 'Red & White Cooperatives (Nunumeu)', 'KOPERASI'::public.supplier_type, 'Banana & Vegetables', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Contract', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E15', 'Aneka', 'INFORMAL'::public.supplier_type, 'Fresh Chicken', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Roster', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E16', 'CV Sangandolu', 'CV'::public.supplier_type, 'Dry condiments', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Roster', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;
insert into public.suppliers (id, name, type, commodity, pic, phone, address, email, notes, score, status, active) values ('SUP-E17', 'PS Mart', 'INFORMAL'::public.supplier_type, 'Dry condiments & Rice', null, null, 'Kupang', null, 'Excel Apr 2026 · Vendor type: Roster', 75.0, 'signed'::public.supplier_status, true) on conflict (id) do update set name = excluded.name, type = excluded.type, commodity = excluded.commodity, pic = coalesce(excluded.pic, public.suppliers.pic), phone = coalesce(excluded.phone, public.suppliers.phone), address = excluded.address, notes = excluded.notes, status = excluded.status, active = true;

-- =============================================================================
-- END 0024
-- =============================================================================
